version: "3.9"

services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    env_file:
    .env                    # ← add this
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}   # ← was hardcoded
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  fastapi-app:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    env_file: 
     .env
    environment:
      DATABASE_URL: ${DATABASE_URL} 

volumes:
  mysql_data: